add_rules("mode.debug", "mode.release")
add_includedirs("includes")
set_languages("c++23")
set_encodings("utf-8")
-- add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

target("llvm")
    set_kind("binary")
    set_toolchains("clang")
    set_runtimes("c++_shared")
    set_policy("build.c++.modules", true)
    add_files("src/*.cpp", "src/*.mpp")
    add_packages("liburing")
    add_linkdirs("/usr/local/lib/x86_64-unknown-linux-gnu")
    add_rpathdirs("/usr/local/lib/x86_64-unknown-linux-gnu")
    add_tests("test", { files = "test/test.cpp", remove_files = "src/main.cpp" })

-- target("gnu")
--     set_kind("binary")
--     set_toolchains("gcc")
--     set_runtimes("stdc++_shared")
--     set_policy("build.c++.modules", true)
--     set_policy("build.c++.modules.gcc.cxx11abi", true)
--     add_files("src/*.cpp", "src/*.mpp")
--     add_packages("liburing")
--     add_linkdirs("/usr/local/lib/../lib64")
--     add_rpathdirs("/usr/local/lib/../lib64")
--     add_tests("test", { files = "test/test.cpp", remove_files = "src/main.cpp" })
